INSERT INTO products
    (product_name, department_name, price, stock_quantity, name_that_reference)
VALUES
    ("Rabbit Of Caerbannog", "Weapons", 10.99, 100, "Monty Python and the Holy Grail"),
    ("Holy Hand Grenade of Antioch", "Weapons", 11, 100, "Monty Python and the Holy Grail"),
    ("VISOR", "Technology", 0, 100, "Star Trek: TNG"),
    ("Sonic Screwdriver", "Technology", 29.99, 130, "Doctor Who"),
    ("TIE Fighter", "Vehicles", 999999.99, 100, "Star Wars"),
    ("Needle", "Weapons", 1000, 100, "Game of Thrones"),
    ("Earthrealm", "Property", 9.99, 100, "Mortal Kombat"),
    ("Icosahedron / D20", "Magical Items", 0.99, 1000, "D&D"),
    ("Dethlock Vinyl Collection", "Weapons", 420.69, 50, "Metalocalypse"),
    ("Aughra's Eye", "Magical Items", 29.99, 100, "The Dark Crystal"),
    ("Sunken City of R'lyeh", "Property", 666, 100, "The Call of Cthulthu"),
    ("Barbasol Shaving Cream + Hidden Compartment", "Technology", 500, 100, "Jurassic Park"),
    ("Evenstar", "Jewelry", 19.99, 100, "Lord of the Rings"),
    ("Sting", "Weapons", 1000, 100, "Lord of the Rings"),
    ("Mound of Dead Bards", "Defense", 5, 1000, "Gamers: Dorkness Rising"),
    ("1967 Chevrolet Impala", "Vehicles", 35000, 100, "Supernatural"),
    ("Countdown Teapot Trophy", "Trophies", 50, 1310, "IT Crowd"),
    ("Eternal Flame", "Weapons", 9000, 100, "Thor: Ragnarok"),
    ("Psychedelic Yam", "Drugs", 10, 100, "Swamp Thing"),
    ("Lasette", "Drugs", 9999999, 1, "Lasette"),
    ("Chakram", "Weapons", 1000, 100, "Xena: Warrior Princess"),
    ("Kurgan Sword", "Weapons", 5000, 100, "Highlander"),
    ("Remembrall", "Magical Items", 75.99, 100, "Harry Potter and the Philosopher's Stone"),
    ("Japanese Peace Lily", "Plants", 11.99, 100, "Hot Fuzz"),
    ("Painting of Happy Little Trees", "Art", 9999.99, 403, "The Joy of Painting: Bob Ross"),
    ("One-Eyed Willy's Treasure Map", "Art", 60, 100, "Goonies"),
    ("The Killer Joke/The Funniest Joke in the World", "Weapons", 5555.99, 1, "Monty Pythons Flying Circus"),
    ("Pretty Floral Bonnet", "Clothing", 5.99, 100, "Firefly"),
    ("Jayne's Hat", "Clothing", 99.99, 100, "Firefly"),
    ("Death Ray (formerly Stun Ray)", "Weapons", 600, 100, "Dr. Horrible's Sing-Along-Blog"),
    ("Flux Capacitor", "Technology", 500, 100, "Back to the Future"),
    ("Babel Fish", "Technology", 1.99, 100, "The Hitchhiker's Guide to the Galaxy"),
    ("Towel", "Clothing", 13.99, 100, "The Hitchhiker's Guide to the Galaxy"),
    ("Book of Shadows", "Magical Items", 600000, 100, "Charmed 2.0"),
    ("Luna Lovegood's Glasses", "Jewelry", 19.99, 100, "Harry Potter and the Order of the Phoenix"),
    ("Audrey II", "Plants", 2.99, 100, "Little Shop of Horrors"),
    ("Adamantium Shield", "Defense", 18000, 100, "Captain America"),
    ("Quidditch Cup", "Trophies", 5000, 100, "Harry Potter")
    